# Definice status LED (použijte vestavěnou nebo připojenou LED)
light:
  - platform: status_led
    id: status_led_1
    name: "Status LED"
    pin: GPIO8  # Upravte podle vašeho HW (např. vestavěná LED na GPIO2)
    restore_mode: ALWAYS_OFF  # Vypnout LED po startu
    
# Řešení problému s okamžitým spánkem
globals:
  - id: first_boot
    type: bool
    restore_value: true
    initial_value: "true"
  - id: sleep_requested
    type: bool
    initial_value: "false"
# interval mezi měřeními
  - id: measure_interval
    type: int
    initial_value: '120'
    restore_value: true

binary_sensor:
  - platform: status
    name: "Status"
    on_press:  # Při připojení
      then:
        - light.turn_on: status_led_1
        - delay: 200ms
        - light.turn_off: status_led_1
    on_release:  # Při ztrátě spojení
      then:
        - light.turn_off: status_led_1

# Napájecí piny pro senzory
output:
  - platform: gpio
    pin: GPIO4
    id: power_sensor1
  - platform: gpio
    pin: GPIO5
    id: power_sensor2
  - platform: gpio
    pin: GPIO6
    id: power_sensor3

sensor:
  - platform: adc
    pin: GPIO0
    name: "Soil Moisture 1"
    id: soil1
    attenuation: 12db
    update_interval: never
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 1.0 -> 100.0
      - sliding_window_moving_average:
          window_size: 3
    on_value:
      then:
        - output.turn_off: power_sensor1
        - globals.set:
            id: sleep_requested
            value: "true"

  - platform: adc
    pin: GPIO1
    name: "Soil Moisture 2"
    id: soil2
    attenuation: 12db
    update_interval: never
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 1.0 -> 100.0
      - sliding_window_moving_average:
          window_size: 3
    on_value:
      then:
        - output.turn_off: power_sensor2
        - globals.set:
            id: sleep_requested
            value: "true"

  - platform: adc
    pin: GPIO3
    name: "Soil Moisture 3"
    id: soil3
    attenuation: 12db
    update_interval: never
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 1.0 -> 100.0
      - sliding_window_moving_average:
          window_size: 3
    on_value:
      then:
        - output.turn_off: power_sensor3
        - globals.set:
            id: sleep_requested
            value: "true"

deep_sleep:
  id: deep_sleep_mode
  run_duration: 120s  # Maximální doba běhu před usnutím

interval:
  - interval: 100ms
    then:
      - output.turn_on: power_sensor1
      - output.turn_on: power_sensor2
      - output.turn_on: power_sensor3
      - delay: 200ms

  - interval: 500ms
    then:
      - if:
          condition:
            wifi.connected:
          then:
            - logger.log: "WiFi is connected!"
            - component.update: soil1
            - component.update: soil2
            - component.update: soil3
            - delay: 200ms
          else:
            - logger.log: "zapínám WiFi"
            - wifi.enable:

  - interval: 2s  # Po dokončení měření
    then:
      - if:
          condition:
            lambda: |-
              return id(sleep_requested) && !id(first_boot);
          then:
            - logger.log: "Příprava na deep sleep"
            - output.turn_off: power_sensor1
            - output.turn_off: power_sensor2
            - output.turn_off: power_sensor3
            - light.turn_off: status_led_1
            - delay: 100ms
            - deep_sleep.enter:
                id: deep_sleep_mode
                sleep_duration: !lambda |-
                  int interval = id(measure_interval);
                  return interval * 1000;

  - interval: 3min
    then:
      - if:
          condition:
            lambda: "return id(first_boot);"
          then:
            - logger.log: "Dokončuji první boot"
            - globals.set:
                id: first_boot
                value: "false"
            - globals.set:
                id: sleep_requested
                value: "true"
